#!/bin/bash

DOTS_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

cat <<'EOF'
      _                     _                        _       _
     | |                   | |                      | |     | |
  ___| |__   __ _ _ __ ___ | |__   ___ _ __ ___   __| | ___ | |_ ___
 / __| '_ \ / _` | '_ ` _ \| '_ \ / _ \ '__/ __| / _` |/ _ \| __/ __|
| (__| | | | (_| | | | | | | |_) |  __/ |  \__ \| (_| | (_) | |_\__ \
 \___|_| |_|\__,_|_| |_| |_|_.__/ \___|_|  |___(_)__,_|\___/ \__|___/

EOF

if [ $# -eq 1 ] && [ $1 == "sync" ]; then
    git --git-dir=$DOTS_DIR/.git pull
    echo
fi

ansible-playbook $DOTS_DIR/playbook.yml --vault-password-file $DOTS_DIR/password

