#!/bin/bash

DOTS_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

cat <<'EOF'
 ______     __  __     ______     __    __     ______     ______     ______     ______
/\  ___\   /\ \_\ \   /\  __ \   /\ "-./  \   /\  == \   /\  ___\   /\  == \   /\  ___\
\ \ \____  \ \  __ \  \ \  __ \  \ \ \-./\ \  \ \  __<,  \ \  __\   \ \  __<,  \ \___  \
 \ \_____\  \ \_\ \_\  \ \_\ \_\  \ \_\ \ \_\  \ \_____\  \ \_____\  \ \_\ \_\  \/\_____\
  \/_____/   \/_/\/_/   \/_/\/_/   \/_/  \/_/   \/_____/   \/_____/   \/_/\/_/   \/_____/

EOF

if [ $# -eq 1 ] && [ $1 == "sync" ]; then
    git --git-dir=$DOTS_DIR/.git pull
fi

ansible-playbook $DOTS_DIR/playbook.yml --vault-password-file $DOTS_DIR/password

