require("chambers/autocmds")
require("chambers/keymaps")
require("chambers/lazy")
require("chambers/options")
require("chambers/ui")

require("chambers/plugins/autopairs")
require("chambers/plugins/cmp")
require("chambers/plugins/comment")
require("chambers/plugins/gitsigns")
require("chambers/plugins/harpoon")
require("chambers/plugins/ls")
require("chambers/plugins/lualine")
require("chambers/plugins/mason")
require("chambers/plugins/telescope")
require("chambers/plugins/tree")
require("chambers/plugins/treesitter")

