---
- name: .dotfiles
  hosts: localhost
  vars:
    current_shell: "{{ lookup('env', 'SHELL') }}"
  vars_files:
    - secrets.yml
  tasks:
    - name: Symlink .vimrc
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.vimrc"
        dest: ~/.vimrc
        state: link
        force: true

    - name: Symlink .tmux.conf
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.tmux.conf"
        dest: ~/.tmux.conf
        state: link
        force: true

    - name: Symlink .aliasrc
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.aliasrc"
        dest: "~/.aliasrc"
        state: link
        force: true

    - name: Symlink .bashrc
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.bashrc"
        dest: ~/.bashrc
        state: link
        force: true
      when: current_shell.endswith('bash')

    - name: Symlink .bash_profile
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.bash_profile"
        dest: ~/.bash_profile
        state: link
        force: true
      when: current_shell.endswith('bash')

    - name: Symlink .zshrc
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.zshrc"
        dest: ~/.zshrc
        state: link
        force: true
      when: current_shell.endswith('zsh')

    - name: Symlink .zshenv
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.zshenv"
        dest: ~/.zshenv
        state: link
        force: true
      when: current_shell.endswith('zsh')

    - name: Symlink .zsh_profile
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.zsh_profile"
        dest: ~/.zsh_profile
        state: link
        force: true
      when: current_shell.endswith('zsh')

    - name: Ensure .config directory exists
      ansible.builtin.file:
        path: ~/.config
        state: directory
        mode: 0755

    - name: Symlink .config/kitty/
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.config/kitty"
        dest: ~/.config/kitty
        state: link
        force: true

    - name: Symlink .config/fastfetch/
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.config/fastfetch"
        dest: ~/.config/fastfetch
        state: link
        force: true

    - name: Symlink .config/nvim/
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.config/nvim"
        dest: ~/.config/nvim
        state: link
        force: true

    - name: Symlink .gitconfig
      ansible.builtin.file:
        src: "{{ playbook_dir }}/.gitconfig"
        dest: ~/.gitconfig
        state: link
        force: true

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: 0700

    - name: Deploy the private ssh key
      ansible.builtin.copy:
        dest: ~/.ssh/id_ed25519
        content: "{{ id_ed25519 }}"
        mode: 0600

    - name: Deploy the public ssh key
      ansible.builtin.copy:
        dest: ~/.ssh/id_ed25519.pub
        content: "{{ id_ed25519_pub }}"
        mode: 0644
...
